# Generated by Django 5.2.1 on 2025-07-06 16:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Notice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название уведомления')),
                ('day_before', models.IntegerField(help_text='0 - в тот же день', verbose_name='За сколько дней напоминать')),
                ('time_send', models.TimeField(verbose_name='Время отправки уведомления')),
                ('creator', models.CharField(blank=True, max_length=100, null=True, verbose_name='Создатель уведомления')),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.CharField(max_length=100, unique=True, verbose_name='ID чата в Telegram')),
                ('user_name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя пользователя')),
                ('time_zone', models.CharField(blank=True, max_length=50, null=True, verbose_name='Часовой пояс')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название платежа')),
                ('cost', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма платежа')),
                ('day', models.DateField(verbose_name='Дата платежа')),
                ('notice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='api.notice', verbose_name='Связанное уведомление')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Платеж',
                'verbose_name_plural': 'Платежи',
            },
        ),
        migrations.AddField(
            model_name='notice',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notices', to='api.user', verbose_name='Пользователь'),
        ),
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Название события')),
                ('date', models.DateField(verbose_name='Дата события')),
                ('time', models.TimeField(blank=True, null=True, verbose_name='Время события')),
                ('notice', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='events', to='api.notice', verbose_name='Связанное уведомление')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.user', verbose_name='Пользователь')),
            ],
            options={
                'verbose_name': 'Событие',
                'verbose_name_plural': 'События',
            },
        ),
    ]
