# Generated by Django 5.2.1 on 2025-07-06 16:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='chat_id',
            field=models.BigIntegerField(unique=True, verbose_name='ID чата в Telegram'),
        ),
    ]
